# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "PACKAGES" ("ID" UUID NOT NULL PRIMARY KEY,"NAME" VARCHAR(254) NOT NULL,"CREATOR_ID" UUID NOT NULL,"ASSIGNEE_ID" UUID NOT NULL,"CC_LIST" VARCHAR(254) NOT NULL,"STATUS" VARCHAR(254) NOT NULL,"OS_VERSION" VARCHAR(254) NOT NULL,"CREATION_TIME" TIMESTAMP NOT NULL,"LAST_UPDATED" TIMESTAMP NOT NULL);
create table "users" ("ID" SERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR(254) NOT NULL,"EMAIL" VARCHAR(254) NOT NULL);

# --- !Downs

drop table "PACKAGES";
drop table "users";

